package simple.data.warehouse

import grails.core.GrailsApplication
import grails.plugins.*

/**
 * Generated by Grails Application Forge
 * We could remove this but lets that leave it here
 * */

class ApplicationController implements PluginManagerAware {

    GrailsApplication grailsApplication
    GrailsPluginManager pluginManager

    def index() {
        [grailsApplication: grailsApplication, pluginManager: pluginManager]
    }
}
